import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "1",
    name: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    image:
      "https://literatureglobe.com/wp-content/uploads/2020/10/Rich-Dad-Poor-Dad-Front-min-e1601808025506.jpg",
    category: "Business",
    oldPrice: 700,
    newPrice: 400,
    discount: 30,
    rating: 4.1,
    isInStock: true,
  },
  {
    _id: "2",
    name: "The 5 AM Club",
    author: "Robin Sharma",
    image:
      "https://5.imimg.com/data5/XE/DD/AO/SELLER-19351533/the-5-am-club-own-your-morning-elevate-your-life-robin-sharma-250x250.jpg",
    category: "Business",
    oldPrice: 600,
    newPrice: 402,
    discount: 33,
    rating: 4.5,
    isInStock: true,
  },
  {
    _id: "3",
    name: "Subtle Art of Not...",
    author: "Mark Manson",
    image:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1465761302i/28257707._UY400_SS400_.jpg",
    category: "Motivation",
    oldPrice: 800,
    newPrice: 400,
    discount: 50,
    rating: 4.1,
    isInStock: true,
  },
  {
    _id: "4",
    name: "Sherlock Holmes",
    author: "Sir Arthur Conan Doyle",
    image:
      "https://m.media-amazon.com/images/I/415FBJlfUfL._SX331_BO1,204,203,200_.jpg",
    category: "Comics",
    oldPrice: 499,
    newPrice: 299,
    discount: 20,
    rating: 3.2,
    isInStock: false,
  },
  {
    _id: "5",
    name: "Diary of a Wimpy Kid",
    author: "Jeff Kinney",
    image:
      "https://m.media-amazon.com/images/I/51T6mDOH41L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Comics",
    oldPrice: 1200,
    newPrice: 900,
    discount: 30,
    rating: 4.2,
    isInStock: true,
  },
  {
    _id: "6",
    name: "The Girl Who Drank the Moon",
    author: "Kelly Barnhill",
    image:
      "https://m.media-amazon.com/images/I/51CmZgnxeXL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Comics",
    oldPrice: 399,
    newPrice: 259,
    discount: 35,
    rating: 2.6,
    isInStock: true,
  },
  {
    _id: "7",
    name: "The Blue Umbrella",
    author: "Ruskin Bond",
    image:
      "https://m.media-amazon.com/images/I/51TGU8igF-L._SX310_BO1,204,203,200_.jpg",
    category: "Comics",
    oldPrice: 155,
    newPrice: 50,
    discount: 37,
    rating: 1.5,
    isInStock: true,
  },
  {
    _id: "8",
    name: "The Four Agrements",
    author: "Don Miguel Ruiz",
    image:
      "https://m.media-amazon.com/images/I/51EA+bXwJsL._SY344_BO1,204,203,200_.jpg",
    category: "Motivation",
    oldPrice: 700,
    newPrice: 500,
    discount: 20,
    rating: 4.7,
    isInStock: true,
  },
  {
    _id: "9",
    name: "The Art Of War",
    author: "Sun Tzu",
    image:
      "https://m.media-amazon.com/images/I/31Ym1oKlpLL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Motivation",
    oldPrice: 420,
    newPrice: 320,
    discount: 10,
    rating: 3.1,
    isInStock: true,
  },
  {
    _id: "10",
    name: "Think and Grow Rich",
    author: "Napoleon Hill",
    image:
      "https://m.media-amazon.com/images/I/51ugqPxmyrL._SX332_BO1,204,203,200_.jpg",
    category: "Motivation",
    oldPrice: 700,
    newPrice: 500,
    discount: 20,
    rating: 4.7,
    isInStock: true,
  },
  {
    _id: "11",
    name: "Switch",
    author: "Chip Heath",
    image:
      "https://m.media-amazon.com/images/I/41pfm3UZ7ZL._SX346_BO1,204,203,200_.jpg",
    category: "Motivation",
    oldPrice: 1150,
    newPrice: 950,
    discount: 20,
    rating: 3.9,
    isInStock: true,
  },
  {
    _id: "12",
    name: "The Psychology of Money",
    author: "Morgan Housel",
    image:
      "https://m.media-amazon.com/images/I/41r6F2LRf8L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Business",
    oldPrice: 399,
    newPrice: 210,
    discount: 47,
    rating: 2.1,
    isInStock: true,
  },
  {
    _id: "13",
    name: "Roller Coaster: An Affair with Banking",
    author: "Tamal Bandyopadhyay",
    image:
      "https://m.media-amazon.com/images/I/41zsr-nxMNL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Business",
    oldPrice: 499,
    newPrice: 341,
    discount: 31,
    rating: 1.8,
    isInStock: true,
  },
  {
    _id: "14",
    name: "Don't Sell Make them Buy",
    author: "R. Mukund",
    image:
      "https://m.media-amazon.com/images/I/41wUJ8vBmWL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    category: "Business",
    oldPrice: 295,
    newPrice: 197,
    discount: 33,
    rating: 1.8,
    isInStock: true,
  },
  {
    _id: "15",
    name: "Grandparents'",
    author: "Sudha Murty",
    image:
      "https://m.media-amazon.com/images/I/51GCJ4sNgpL._SX323_BO1,204,203,200_.jpg",
    category: "Comics",
    oldPrice: 250,
    newPrice: 180,
    discount: 28,
    rating: 3.5,
    isInStock: true,
  },
];
